# This code is intended to be used **for training purposes only**.
development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: Sample-App_production
